---
title: "KAP Contraception Exploratory"
author: ''
date: "`r format(Sys.Date(), '%b %d, %Y')`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
source("../.Rprofile")
library(compareGroups)
```

```{r}
kap_contraception <- readRDS(paste0(path_kap_contraception,"/working/kap_contraception.RDS")) 

kap_contraception <- kap_contraception %>% 
  dplyr::select(sno, sage, so,d_sed,sms,smsd,slc,
                skppc:spub,saiucde,sals,spiucd:scfdi,
                
                starts_with("d_")) %>% 
  dplyr::mutate(slc = as.factor(slc)) %>% 
  labelled::copy_labels(kap_contraception, .)
```


## Demographics

```{r}
kap_contraception %>% 
  dplyr::select(sage, so,d_sed,sms,smsd,slc) %>% 
  compareGroups(~ ., data=.) %>% 
  createTable(.,show.all=TRUE,show.p.overall = FALSE,digits=1,
              hide="0, No",show.n = TRUE) %>% 
  export2md()
```

\pagebreak

## Knowledge and Attitude

```{r}

kap_contraception %>% 
  dplyr::select(skppc:spub,saiucde,sals,spiucd:scfdi) %>% 
compareGroups(~ ., data=.) %>% 
  createTable(.,show.all=TRUE,show.p.overall = FALSE,digits=1,
              hide="0, No",show.n = TRUE) %>% 
  export2md()
```

\pagebreak

## IUCD vs Pill

```{r}
kap_contraception %>% 
  dplyr::select(starts_with("d_"),-d_sed) %>% 
  compareGroups(~ ., data=.) %>% 
  createTable(.,show.all=TRUE,show.p.overall = FALSE,digits=1,
              hide="0, No",show.n = TRUE) %>% 
  export2md()
```

